{% set name = "ldas-tools-cmake" %}
{% set version = "1.1.0" %}
{% set sha256 = "748998a3bcd5c89ae7c23950f7503dc8e0233bca40adf15a6b3fe836f03e96ce" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake >=3.2

test:
  commands:
    - exit $(test -f ${PREFIX}/share/ldas-tools/cmake/Modules/LDASToolsInstallDirs.cmake)  # [not win]
    - exit $(test -f ${PREFIX}/share/ldas-tools/cmake/Modules/Autotools/ArchiveX/cx_ldas_pkg_check.cmake)  # [not win]
    - exit $(test -f ${PREFIX}/lib/pkgconfig/ldastoolscmake.pc)  # [not win]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\LDASToolsInstallDirs.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\Autotools\ArchiveX\cx_ldas_pkg_check.cmake exit 1  # [win]

about:
  home: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPLv2+
  license_family: GPL
  license_file: COPYING
  summary: CMake functions used by LDAS Tools

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
