{% set name = "ldas-tools-cmake" %}
{% set version = "1.0.6" %}
{% set sha256 = "93c6ad661058c0370a0ed252ff17df17a99cdd321b7464cc347ca61c1253b491" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000

requirements:
  build:
    - cmake >=3.6
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - exit $(test -f ${PREFIX}/share/ldas-tools/cmake/Modules/LDASToolsInstallDirs.cmake)  # [not win]
    - exit $(test -f ${PREFIX}/share/ldas-tools/cmake/Modules/Autotools/ArchiveX/cx_ldas_pkg_check.cmake)  # [not win]
    - exit $(test -f ${PREFIX}/lib/pkgconfig/ldastoolscmake.pc)  # [not win]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\LDASToolsInstallDirs.cmake exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\Autotools\ArchiveX\cx_ldas_pkg_check.cmake exit 1  # [win]

about:
  home: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPLv2+
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: CMake functions used by LDAS Tools

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
