{% set name = "ldas-tools-cmake" %}
{% set version = "1.2.3" %}
{% set sha256 = "23aa4d18e9ba17e71d868955949af363267ea0630331892326c169ac0b363580" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  ignore_run_exports:
    # we don't actually use the compiler
    - libgcc-ng  # [linux]
    - libstdcxx-ng  # [linux]
    - vc  # [win]
    - vs2015_runtime  # [win]
  number: 0

requirements:
  build:
    # we need a compiler present, osx has one by default
    - {{ compiler('c') }}  # [not osx]
    - {{ compiler('cxx') }}  # [not osx]
    - cmake >=3.2
    - pkg-config
  host:
    - igwn-cmake >=1.2.1
  run:
    - igwn-cmake >=1.2.1

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - test -f ${PREFIX}/share/ldas-tools/cmake/Modules/LDASToolsCMakeConfig.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\LDASToolsCMakeConfig.cmake exit 1  # [win]
    - test "$(pkg-config --modversion ldastoolscmake)" == "{{ version }}"  # [unix]

about:
  home: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: CMake functions used by LDAS Tools

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
