{% set name = "ldas-tools-cmake" %}
{% set version = "1.2.3" %}

# dependency versions
{% set igwn_cmake_macros_version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 23aa4d18e9ba17e71d868955949af363267ea0630331892326c169ac0b363580

build:
  ignore_run_exports:
    # we don't actually use the compiler, but need it to configure cmake
    - libgcc-ng  # [linux]
    - libstdcxx-ng  # [linux]
    - vc  # [win]
    - vs2015_runtime  # [win]
  number: 0

requirements:
  build:
    # we need a compiler present, osx has one by default
    - {{ compiler('c') }}  # [not osx]
    - {{ compiler('cxx') }}  # [not osx]
    - cmake >=3.2
    - pkg-config
  host:
    - igwn-cmake-macros >={{ igwn_cmake_macros_version }}
  run:
    - igwn-cmake-macros >={{ igwn_cmake_macros_version }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    # check files exist
    - test -f ${PREFIX}/share/ldas-tools/cmake/Modules/LDASToolsCMakeConfig.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\share\ldas-tools\cmake\Modules\LDASToolsCMakeConfig.cmake exit 1  # [win]
    # check pkg-config
    - pkg-config --exact-version {{ version }} ldastoolscmake  # [unix]

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: CMake functions used by LDAS Tools
  description: |
    This collection of cmake macros was developed as part of
    the LDAS Tools Suite to have consistency across all of the packages

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
